### ISSUE TITLE
Invalid headers

### ISSUE THREAD

**Issue by geoff-liddiard** [mikepugh/prerender-parse#1]
prerenderio.js line 21 
`res.set(prerenderedResponse.headers);`

causeing a timeout / 500 error - invalid headers
example: http://happidev.parseapp.com/?_escaped_fragment_=

The headers object looks like this: 
`{"Connection":"keep-alive","Content-Encoding":"gzip","Content-Length":"1659","Content-Type":"text/html;charset=UTF-8","Date":"Tue, 24 Jun 2014 08:42:08 GMT","Server":"nginx/1.4.2","Via":"1.0 localhost (squid/3.1.19)","X-Cache":"MISS from localhost","X-Cache-Lookup":"MISS from localhost:3128"}`

Possibly related to this: https://github.com/zf-fr/zfr-prerender/issues/13

**Comment by mikepugh** [comment]
No updates in 2 years - closing
